# This file was generated by GoReleaser. DO NOT EDIT.
class Bifrost < Formula
  desc "The CLI tools for Fortress"
  homepage "https://d.foundation"
  version "0.5.1"
  bottle :unneeded

  if OS.mac?
    url "https://storage.googleapis.com/dwarvesf/bifrost/v0.5.1/bifrost_darwin_amd64.tar.gz"
    sha256 "f8fd3bfb0831f12ec4d752d48487f85373bab9e5f21b05416427b76a85158daf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://storage.googleapis.com/dwarvesf/bifrost/v0.5.1/bifrost_linux_amd64.tar.gz"
      sha256 "f29a5f61cf9d91ccbc5bd20df2d9b7caa600c0fe7b41f7bd793fded7676174c7"
    end
  end

  def install
    bin.install "bifrost"
  end
end
